Molecular_Methods_Project/urls.py
from django.conf.urls import patterns, include, url
from yawdadmin import admin_site

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
admin_site._registry.update(admin.site._registry)

#Add any extra urls to applications or maybe log-in screen
urlpatterns = patterns('',
    # Examples:

    # url(r'^$', 'Molecular_Methods_Project.views.home', name='home'),
    # url(r'^Molecular_Methods_Project/', include('Molecular_Methods_Project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin_site.urls)),

    url(r'^app/', include('app.urls', namespace='app')),
    url(r'', include('app.urls', namespace='app')),
)

app/urls.py
from django.conf.urls import patterns,include, url
from app import views
from django.conf import settings
from django.contrib import admin

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^index/$', views.index, name='index'),
        url(r'^glossary/$', views.glossary, name='glossary'),
        url(r'^labs/$', views.labs, name='labs'),
        url(r'^admin/$', include(admin.site.urls)),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^videos/$', views.videos, name='videos'),
        url(r'^primersquizzes/$', views.primersquizzes, name='primersquizzes'),
        url(r'^checkans/$', views.checkans, name='checkans'),
        url(r'^generalquizzes/$', views.generalquizzes, name='generalquizzes'),
        url(r'^restrictionquizzes/$', views.restrictionquizzes, name='restrictionquizzes'),
        url(r'^dataquizzes/$', views.dataquizzes, name='dataquizzes'),
        url(r'^pcrlab/$', views.pcrlab, name='pcrlab'),
        url(r'^ligation/$', views.ligation, name='ligation'),
        url(r'^bwscreening/$', views.bwscreening, name='bwscreening'),
        url(r'^plasmid/$', views.plasmid, name='plasmid'),
        url(r'^dna/$', views.dna, name='dna'),
        url(r'^quantpcr/$', views.quantpcr, name='quantpcr'),
        url(r'^revision/$', views.revision, name='revision'),
        url(r'^converterconcentration/$', views.converterconcentration, name='converterconcentration'),
        url(r'^converterdilutions/$', views.converterdilutions, name='converterdilutions'),
        url(r'^convertermass/$', views.convertermass, name='convertermass'),
        url(r'^convertermolarity/$', views.convertermolarity, name='convertermolarity'),
        url(r'^convertervolume/$', views.convertervolume, name='convertervolume'),
        url(r'^mapping/$', views.mapping, name='mapping'),
        url(r'^pcrlabpdf/$', views.pcr_pdf_view, name='pcrlabpdf'),
        url(r'^ligationlabpdf/$', views.ligation_pdf_view, name='ligationlabpdf'),
        url(r'^bwslabpdf/$', views.bws_pdf_view, name='bwslabpdf'),
        url(r'^plasmidlabpdf/$', views.plasmid_pdf_view, name='plasmidlabpdf'),
        url(r'^dnalabpdf/$', views.dna_pdf_view, name='dnalabpdf'),
        url(r'^qpcrlabpdf/$', views.qpcr_pdf_view, name='qpcrlabpdf'),
        url(r'^Electrophoresis/$', views.electro_pdf_view, name='Electrophoresis'),
        url(r'^Sequence_Analysis/$', views.sa_pdf_view, name='Sequence_Analysis'),
        url(r'^Ligation_Calculations/$', views.lc_pdf_view, name='Ligation_Calculations'),
        url(r'^QPCR_Exercises/$', views.qpcrexer_pdf_view, name='QPCR_Exercises'),
        url(r'^Primer_Design_Exercise/$', views.pdexer_pdf_view, name='Primer_Design_Exercise'),
        url(r'^Restriction_Mapping_Exercise/$', views.rmexer_pdf_view, name='Restriction_Mapping_Exercise'),
        url(r'^lab_manual_pdf/$', views.lab_manual_pdf_view, name='lab_manual_pdf'),
        # end pdfs
        url(r'^searchResult/$', views.search, name='searchResult'),
        url(r'^resetConfirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/',views.reset_confirm, name='resetConfirm'),
        url(r'^pwdReset/', views.reset, name='pwdReset'),
        url(r'^about/', views.contact, name='about'),
        url(r'^thanks/', views.thanks, name='thanks'),

)


if settings.DEBUG:
        urlpatterns += patterns(
                'django.views.static',
                (r'static/(?P<path>.*)',
                'serve',
                {'document_root': settings.STATIC_ROOT}), )

templates/labs/bwscreening.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
    <!--start: Container -->
    <div class="container">
        <!--start: Wrapper-->
        {% include "navigation.html" %}

        <div id="wrapper">
            <div class="row row-centered">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 align-left">
                    <div>
                        <h1 class="blue-heading-h1"><span>Blue/White Screening</span></h1>
                        <br>
                        <h3 class="blue-heading-h3"><span style="color:darkblue;font-weight:bold">Intended Learning Outcomes</span></h3>
                        <ul class="square_list"><li><span style="color:black">Explain the principles and purpose of antibiotic selection and blue/white screening </span></li></ul>
                        <ul class="square_list"><li><span style="color:black">Understand your agar plates and class controls</span></li></ul>

                        <h3 class="blue-heading-h3"><span style="color:darkblue;font-weight:bold">Task List</span></h3>
                        <ul class="square_list"><li><span style="color:black">Analyse agar plates, including all controls</span></li></ul>
                        <ul class="square_list"><li><span style="color:black">Grow blue and white E.coli colonies in liquid culture overnight</span></li></ul>
                    </div>
                    <br>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-1 col-xs-1"><br></div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-8 align-left">
                    <div ><a href="{% url 'app:bwslabpdf' %}"><img src="{% static  'img/lab3-BWS.png' %}" class="img-responsive " alt="Responsive image"/>
                        <div class="image-overlay-link"></div></a> </div>
                    <br>
                    <span style="color:darkblue;"><a href="{% url 'app:bwslabpdf' %}">Method</a></span>
                </div>


            </div>
        </div><!-- end: Wrapper -->
    </div><!-- end: Container -->
{% endblock %}

templates/labs/dna.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
	<!--start: Container -->
	<div class="container">
		<!--start: Wrapper-->
        {% include "navigation.html" %}

            <div id="wrapper">
                <div class="row row-centered">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 align-left">
                    <h1 class="blue-heading-h1">DNA Sequencing </h1>
                    <br>
                    <h3 class="blue-heading-h3"><span style="font-weight:bold">Intended Learning Outcomes</span></h3>
                    <ul class="square_list"><li><span style="color:black">Understand the principle of dideoxy sequencing of a plasmid</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Compare and contrast the theoretical principles of manual and automated sequencing</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Be able to perform and understand DNA sequence analyses</span></li></ul>

                    <h3 class="blue-heading-h3"><span style="font-weight:bold">Task List</span></h3>
                    <ul class="square_list"><li><span style="color:black">Complete the ‘Sequencing’ section of the lab</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Examine and analyse DNA sequence data from the fragment of DNA you have cloned in Computer Exercise ‘Sequence Analysis’</span></li></ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-1 col-xs-1"><br></div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-8 align-left">
                    <div ><a href="{% url 'app:dnalabpdf' %}"><img src="{% static  'img/lab5-DNA.png' %}" class="img-responsive " alt="Responsive image"/>
                        <div class="image-overlay-link"></div></a> </div>
                    <br>
                    <h3><i><span style="color:darkblue;font-weight:bold"><a href="{% url 'app:ligationlabpdf' %}">Method</a></span> </i></h3>
                    <h3><i><span style="color:darkblue;font-weight:bold"><a href="{% url 'app:Sequence_Analysis' %}">Computer Exercise (Incorrect Link) </a></span> </i></h3>
                </div>
                    </div>
            </div><!-- end: Wrapper -->
    </div><!-- end: Container -->
 {% endblock %}

templates/labs/ligation.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
    <!--start: Container -->
    <div class="container">
        <!--start: Wrapper-->
        {% include "navigation.html" %}

        <div id="wrapper">
            <div class="row row-centered">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 align-left">
                    <h3 class="blue-heading-h1"><span>Ligation and Transformation</span></h3>
                    <br>
                    <h3 class="blue-heading-h3"><span style="font-weight:bold">Intended Learning Outcomes</span></h3>
                    <ul class="square_list"><li><span style="color:black">Describe the strategies used in cloning DNA into a suitable plasmid vector</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Describe, and be able to perform, transformation of E.coli with a plasmid</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Be able to perform calculations relating to Molecular Methods, including transformation efficiency, dilutions and concentrations</span></li></ul>

                    <h3 class="blue-heading-h3" cl><span style="font-weight:bold">Task List</span></h3>
                    <ul class="square_list"><li><span style="color:black">Restriction digest PCR sample</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Ligate PCR product into a digested plasmid vector</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Transform E.coli with recombinant plasmid</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Undertake Exercise ‘Calculations’</span></li></ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-1 col-xs-1"><br></div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-8 align-left">
                    <div ><a href="{% url 'app:ligationlabpdf' %}"><img src="{% static  'img/lab2-LaT.png' %}" class="img-responsive " alt="Responsive image"/>
                        <div class="image-overlay-link"></div></a> </div>
                    <br>
                    <h3><i><span style="color:darkblue;font-weight:bold"><a href="{% url 'app:ligationlabpdf' %}">Method</a></span> </i></h3>
                    <h3><i><span style="color:darkblue;font-weight:bold"><a href="{% url 'app:Ligation_Calculations' %}">Lab Exercise</a></span> </i></h3>

                </div>
            </div><!-- end: Wrapper -->
        </div><!-- end: Container -->
{% endblock %}

templates/labs/pcrlab.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
    <!--start: Container -->
    <div class="container">
        <!--start: Wrapper-->
        {% include "navigation.html" %}

        <div id="wrapper">

            <div class="row row-centered">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 align-left">
                    <h1 class="blue-heading-h1">PCR</h1>
                    <br>
                    <h3 class="blue-heading-h3"><span style="font-weight:bold">Intended Learning Outcomes</span></h3>
                    <ul class="square_list"><li><span style="color:black">Describe the theory of, and be able to design and perform, a polymerase chain reaction (PCR) reaction</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Understand the principles behind PCR primer design</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Analyse PCR results from gel electrophoresis</span></li></ul>

                    <h3 class="blue-heading-h3"><span style="font-weight:bold">Task List</span></h3>
                    <ul class="square_list"><li><span style="color:black">Set up PCR</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Run PCR</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Perform gel electrophoresis with PCR samples</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Purify the PCR sample</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Analyse results from gel electrophoresis</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Undertake Exercise ‘PCR and Primer Design’</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Undertake Computing Exercise ‘Designing a PCR Experiment’</span></li></ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-1 col-xs-1"><br></div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-8 align-left">
                    <div ><a href="{% url 'app:pcrlabpdf' %}"><img src="{% static  'img/lab1-PCR.png' %}" class="img-responsive " alt="Responsive image"/>
                        <div class="image-overlay-link"></div></a> </div>
                    <br>
                    <h3><i><span style="color:darkblue;font-weight:bold"><a href="{% url 'app:pcrlabpdf' %}">Method</a></span> </i></h3>
                    <h3><i><span style="color:darkblue;font-weight:bold"><a href="{% url 'app:Electrophoresis' %}">Computer Exercise (Incorrect Link)</a></span> </i></h3>
                </div>

            </div>
        </div>
    </div><!-- end: Wrapper -->
    </div><!-- end: Container -->

{% endblock %}

templates/labs/plasmid.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
    <!--start: Container -->
    <div class="container">
        <!--start: Wrapper-->
        {% include "navigation.html" %}

        <div id="wrapper">
            <div class="row row-centered">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 align-left">
                    <h1 class="blue-heading-h1"><span>Plasmid Miniprep</span></h1>
                    <br>
                    <h3 class="blue-heading-h3"><span style="font-weight:bold">Intended Learning Outcomes</span></h3>
                    <ul class="square_list"><li><span style="color:black">Describe and perform a small-scale plasmid purification from an overnight culture</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Understand the concept of, and be able to deduce, a restriction map for a plasmid</span></li></ul>

                    <h3 class="blue-heading-h3"><span style="font-weight:bold">Task List</span></h3>
                    <ul class="square_list"><li><span style="color:black">Harvest and mini-prep E. coli cultures in order to purify plasmids</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Check the success of the cloning procedure by restriction digest and gel electrophoresis</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Undertake Exercise ‘Restriction Mapping’</span></li></ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-1 col-xs-1"><br></div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-8 align-left">
                    <div ><a href="{% url 'app:plasmidlabpdf' %}"><img src="{% static  'img/lab4-PM.png' %}" class="img-responsive " alt="Responsive image"/>
                        <div class="image-overlay-link"></div></a> </div>
                    <br>
                    <h3><i><span style="color:darkblue;font-weight:bold"><a href="{% url 'app:plasmidlabpdf' %}">Method</a></span> </i></h3>
                    <h3><i><span style="color:darkblue;font-weight:bold"><a href="{% url 'app:Restriction_Mapping_Exercise' %}">Lab Exercise</a></span> </i></h3>
                </div>
            </div><!-- end: Wrapper -->
        </div><!-- end: Container -->
{% endblock %}

templates/labs/quantpcr.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
    <!--start: Container -->
    <div class="container">
        <!--start: Wrapper-->
        {% include "navigation.html" %}
        <div id="wrapper">
            <div class="row row-centered">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8 align-left">
                    <h1 class="blue-heading-h1"><span style=>Real-Time Quantitative PCR</span> </h1>
                    <br>
                    <h3 class="blue-heading-h3"><span style="font-weight:bold">Intended Learning Outcomes</span></h3>
                    <ul class="square_list"><li><span style="color:black">Describe the theory of, and be able to design and perform, a real-time quantitative polymerase chain reaction (PCR) reaction</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Understand the different applications of conventional PCR vs RT-qPCR</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Compare and contrast PCR and real-time qPCR</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Analyse real-time qPCR data</span></li></ul>

                    <h3 class="blue-heading-h3"><span style="font-weight:bold">Task List</span></h3>
                    <ul class="square_list"><li><span style="color:black">Design primers to amplify the HIV gene sequence</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Perform gel electrophoresis of conventional PCR</span></li></ul>
                    <ul class="square_list"><li><span style="color:black">Analyse RT-qPCR data in Computing Exercise ‘Real-time qPCR Data Analysis’</span></li></ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-1 col-xs-1"><br></div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-8 align-left">
                    <div ><a href="{% url 'app:qpcrlabpdf' %}"><img src="{% static  'img/lab6-rtqPCR.png' %}" class="img-responsive " alt="Responsive image"/>
                        <div class="image-overlay-link"></div></a> </div>
                    <br>
                    <h3><i><span style="color:darkblue;font-weight:bold"><a href="{% url 'app:qpcrlabpdf' %}">Method</a></span> </i></h3>
                    <h3><i><span style="color:darkblue;font-weight:bold"><a href="{% url 'app:QPCR_Exercises' %}">Computer Exercise</a></span> </i></h3>
                </div><!-- end: Wrapper -->
            </div><!-- end: Container -->
        </div>
    </div>
{% endblock %}