Molecular_Methods_Project/urls.py
from django.conf.urls import patterns, include, url
from yawdadmin import admin_site

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
admin_site._registry.update(admin.site._registry)

#Add any extra urls to applications or maybe log-in screen
urlpatterns = patterns('',
    # Examples:

    # url(r'^$', 'Molecular_Methods_Project.views.home', name='home'),
    # url(r'^Molecular_Methods_Project/', include('Molecular_Methods_Project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin_site.urls)),

    url(r'^app/', include('app.urls', namespace='app')),
    url(r'', include('app.urls', namespace='app')),
)

app/urls.py
from django.conf.urls import patterns,include, url
from app import views
from django.conf import settings
from django.contrib import admin

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^index/$', views.index, name='index'),
        url(r'^glossary/$', views.glossary, name='glossary'),
        url(r'^labs/$', views.labs, name='labs'),
        url(r'^admin/$', include(admin.site.urls)),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^videos/$', views.videos, name='videos'),
        url(r'^primersquizzes/$', views.primersquizzes, name='primersquizzes'),
        url(r'^checkans/$', views.checkans, name='checkans'),
        url(r'^generalquizzes/$', views.generalquizzes, name='generalquizzes'),
        url(r'^restrictionquizzes/$', views.restrictionquizzes, name='restrictionquizzes'),
        url(r'^dataquizzes/$', views.dataquizzes, name='dataquizzes'),
        url(r'^pcrlab/$', views.pcrlab, name='pcrlab'),
        url(r'^ligation/$', views.ligation, name='ligation'),
        url(r'^bwscreening/$', views.bwscreening, name='bwscreening'),
        url(r'^plasmid/$', views.plasmid, name='plasmid'),
        url(r'^dna/$', views.dna, name='dna'),
        url(r'^quantpcr/$', views.quantpcr, name='quantpcr'),
        url(r'^revision/$', views.revision, name='revision'),
        url(r'^converterconcentration/$', views.converterconcentration, name='converterconcentration'),
        url(r'^converterdilutions/$', views.converterdilutions, name='converterdilutions'),
        url(r'^convertermass/$', views.convertermass, name='convertermass'),
        url(r'^convertermolarity/$', views.convertermolarity, name='convertermolarity'),
        url(r'^convertervolume/$', views.convertervolume, name='convertervolume'),
        url(r'^mapping/$', views.mapping, name='mapping'),
        url(r'^pcrlabpdf/$', views.pcr_pdf_view, name='pcrlabpdf'),
        url(r'^ligationlabpdf/$', views.ligation_pdf_view, name='ligationlabpdf'),
        url(r'^bwslabpdf/$', views.bws_pdf_view, name='bwslabpdf'),
        url(r'^plasmidlabpdf/$', views.plasmid_pdf_view, name='plasmidlabpdf'),
        url(r'^dnalabpdf/$', views.dna_pdf_view, name='dnalabpdf'),
        url(r'^qpcrlabpdf/$', views.qpcr_pdf_view, name='qpcrlabpdf'),
        url(r'^Electrophoresis/$', views.electro_pdf_view, name='Electrophoresis'),
        url(r'^Sequence_Analysis/$', views.sa_pdf_view, name='Sequence_Analysis'),
        url(r'^Ligation_Calculations/$', views.lc_pdf_view, name='Ligation_Calculations'),
        url(r'^QPCR_Exercises/$', views.qpcrexer_pdf_view, name='QPCR_Exercises'),
        url(r'^Primer_Design_Exercise/$', views.pdexer_pdf_view, name='Primer_Design_Exercise'),
        url(r'^Restriction_Mapping_Exercise/$', views.rmexer_pdf_view, name='Restriction_Mapping_Exercise'),
        url(r'^lab_manual_pdf/$', views.lab_manual_pdf_view, name='lab_manual_pdf'),
        # end pdfs
        url(r'^searchResult/$', views.search, name='searchResult'),
        url(r'^resetConfirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/',views.reset_confirm, name='resetConfirm'),
        url(r'^pwdReset/', views.reset, name='pwdReset'),
        url(r'^about/', views.contact, name='about'),
        url(r'^thanks/', views.thanks, name='thanks'),

)


if settings.DEBUG:
        urlpatterns += patterns(
                'django.views.static',
                (r'static/(?P<path>.*)',
                'serve',
                {'document_root': settings.STATIC_ROOT}), )

templates/login/login.html
<!doctype html>
<html xmlns="http://www.w3.org/1999/html"><head></head><body>{% load staticfiles %}



<!-- Is anyone getting tired of repeatedly entering the header over and over?? -->
<title>app</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">

<div class="container">
    <div class="modal-dialog">
        <div class="jumbotron">
            <div class="row">
                <h2 class="pull-left" style="color: #005984">Login</h2><a href="#" class=" pull-right">
         <img style="height: 50px; margin-top: -5px;" src=" {% static 'img/logo8.png' %}" alt="logo"></a></div>
            <form id="login_form" method="post" action="{% url 'app:login' %}">
                {% if bad_details %}
                    <p><strong style="color: #00008b">Your username and/or password were incorrect!</strong></p>
                {% elif disabled_account %}
                    <p><strong>Your account is currently disabled; we can't log you in!</strong></p>
                {% endif %}

                {% csrf_token %}
                <input class="input-large form-control" type="text" style="color: #00008b" name="username" value="" id="username" placeholder="Username">
                <input class="input-large form-control" type="password" style="color: #00008b" name="password" value="" id="" placeholder="Password">
                <br>
                <input type="submit" value="Login" class="form-control btn btn-primary btn-lg " style="padding-bottom: 30px" role="button">
                <br><br>
            <div class="btn-group-justified ">
                <a href="{% url 'app:register' %}" class="btn btn-primary btn-lg btn" role="button">Register</a>

                <a href="{% url 'app:pwdReset' %}" class="btn btn-primary btn-lg btn " role="button">Forgot Password?</a>
                </div>
            </form>


        </div>
    </div>
</div>
<!-- start: Java Script -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script defer="defer" src="{% static 'js/custom.js' %}"></script>
<!-- end: Java Script --></body></html>

templates/login/register.html
<!doctype html>
<html><head></head><body>{% load staticfiles %}


<title>app</title>
<!-- Is anyone getting tired of repeatedly entering the header over and over?? -->

<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">



<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script defer="defer" src="{% static 'js/custom.js' %}"></script>

<div class="container">
{#    <div class="modal-dialog">#}

        <div class="jumbotron">
            <div class="row">
                <h2 class="pull-left" style="color: #005984">Register here</h2><a href="#" class=" pull-right">
                <img style="height: 50px; margin-top: -5px;" src=" {% static 'img/logo8.png' %}" alt="logo"></a></div>


            {% if registered %}
                <strong><font size="6" color="#005984">Thank you for registering!</font></strong>
                <br>
                <br>
                <a href="/app"><font size="4" color="#005984">Return to the login page.</font></a><br>
            {% else %}
                {#                </h1><h1 style="color: #00008b">Register here</h1>#}
                 <div class="container">
                <h2 style="color: #005984">Fill in the form to register</h2>
                <form id="user_form" method="post" action="{% url 'app:register' %}" enctype="multipart/form-data">

                    {% csrf_token %}

                    <!-- Display each form. The as_p method wraps each element in a paragraph
                         (<p>) element. This ensures each element appears on a new line,
                         making everything look neater. -->
                    <br>
                    <p><input class="input-large form-control" type="text" style="color: #00008b" name="username" value="" id="username" placeholder="Username">
                    </p>
                    <p><input class="input-large form-control" type="email" style="color: #00008b" name="email" value="" id="email" placeholder="Email">
                    </p>
                    <p><input class="input-large form-control" type="password" style="color: #00008b" name="password" value="" id="password" placeholder="Password">
                    </p>
                    <!-- Provide a button to click to submit the form. -->
                    <input type="submit" name="submit" value="Register" class="form-control btn btn-primary btn-lg" style="padding-bottom: 30px">
                </form>
                </div>
            {% endif %}
        </div>
{#    </div>#}
</div>

<!-- start: Java Script -->
<!-- Placed at the end of the document so the pages load faster -->


<!-- end: Java Script --></body></html>