Molecular_Methods_Project/urls.py
from django.conf.urls import patterns, include, url
from yawdadmin import admin_site

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
admin_site._registry.update(admin.site._registry)

#Add any extra urls to applications or maybe log-in screen
urlpatterns = patterns('',
    # Examples:

    # url(r'^$', 'Molecular_Methods_Project.views.home', name='home'),
    # url(r'^Molecular_Methods_Project/', include('Molecular_Methods_Project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin_site.urls)),

    url(r'^app/', include('app.urls', namespace='app')),
    url(r'', include('app.urls', namespace='app')),
)

app/urls.py
from django.conf.urls import patterns,include, url
from app import views
from django.conf import settings
from django.contrib import admin

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^index/$', views.index, name='index'),
        url(r'^glossary/$', views.glossary, name='glossary'),
        url(r'^labs/$', views.labs, name='labs'),
        url(r'^admin/$', include(admin.site.urls)),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^videos/$', views.videos, name='videos'),
        url(r'^primersquizzes/$', views.primersquizzes, name='primersquizzes'),
        url(r'^checkans/$', views.checkans, name='checkans'),
        url(r'^generalquizzes/$', views.generalquizzes, name='generalquizzes'),
        url(r'^restrictionquizzes/$', views.restrictionquizzes, name='restrictionquizzes'),
        url(r'^dataquizzes/$', views.dataquizzes, name='dataquizzes'),
        url(r'^pcrlab/$', views.pcrlab, name='pcrlab'),
        url(r'^ligation/$', views.ligation, name='ligation'),
        url(r'^bwscreening/$', views.bwscreening, name='bwscreening'),
        url(r'^plasmid/$', views.plasmid, name='plasmid'),
        url(r'^dna/$', views.dna, name='dna'),
        url(r'^quantpcr/$', views.quantpcr, name='quantpcr'),
        url(r'^revision/$', views.revision, name='revision'),
        url(r'^converterconcentration/$', views.converterconcentration, name='converterconcentration'),
        url(r'^converterdilutions/$', views.converterdilutions, name='converterdilutions'),
        url(r'^convertermass/$', views.convertermass, name='convertermass'),
        url(r'^convertermolarity/$', views.convertermolarity, name='convertermolarity'),
        url(r'^convertervolume/$', views.convertervolume, name='convertervolume'),
        url(r'^mapping/$', views.mapping, name='mapping'),
        url(r'^pcrlabpdf/$', views.pcr_pdf_view, name='pcrlabpdf'),
        url(r'^ligationlabpdf/$', views.ligation_pdf_view, name='ligationlabpdf'),
        url(r'^bwslabpdf/$', views.bws_pdf_view, name='bwslabpdf'),
        url(r'^plasmidlabpdf/$', views.plasmid_pdf_view, name='plasmidlabpdf'),
        url(r'^dnalabpdf/$', views.dna_pdf_view, name='dnalabpdf'),
        url(r'^qpcrlabpdf/$', views.qpcr_pdf_view, name='qpcrlabpdf'),
        url(r'^Electrophoresis/$', views.electro_pdf_view, name='Electrophoresis'),
        url(r'^Sequence_Analysis/$', views.sa_pdf_view, name='Sequence_Analysis'),
        url(r'^Ligation_Calculations/$', views.lc_pdf_view, name='Ligation_Calculations'),
        url(r'^QPCR_Exercises/$', views.qpcrexer_pdf_view, name='QPCR_Exercises'),
        url(r'^Primer_Design_Exercise/$', views.pdexer_pdf_view, name='Primer_Design_Exercise'),
        url(r'^Restriction_Mapping_Exercise/$', views.rmexer_pdf_view, name='Restriction_Mapping_Exercise'),
        url(r'^lab_manual_pdf/$', views.lab_manual_pdf_view, name='lab_manual_pdf'),
        # end pdfs
        url(r'^searchResult/$', views.search, name='searchResult'),
        url(r'^resetConfirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/',views.reset_confirm, name='resetConfirm'),
        url(r'^pwdReset/', views.reset, name='pwdReset'),
        url(r'^about/', views.contact, name='about'),
        url(r'^thanks/', views.thanks, name='thanks'),

)


if settings.DEBUG:
        urlpatterns += patterns(
                'django.views.static',
                (r'static/(?P<path>.*)',
                'serve',
                {'document_root': settings.STATIC_ROOT}), )

templates/quizzes/checkquizans.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
	<!--start: Container -->
	<div class="container">
        {% if data %}
            {% for question, corr_ans, user_ans in data %}
                 <!--start: Wrapper-->
                <div id="wrapper">

                    <hr class="clean">

                    <!-- start: Row -->
                    <div class="row">

                        <div align="justified">
                           <h2 class="blue-heading-h2"><b> {% autoescape off %}{{ forloop.counter }}. {{ question }}{% endautoescape %} </b></h2>
                           <br>
                        </div>

                        <div class="span7 portfolio-item" align="left">
                            <h3>Options:</h3>
                            <ol>
                                {% for answer1 in answers %}
                                     {% if answer1.question == question %}
                                         <h3><li><font color="black" size="3"> {% autoescape off %}{{ answer1.answer }}{% endautoescape %} </font></li></h3>
                                         <br>
                                     {% endif %}
                                {% endfor %}
                            </ol>


                        </div>
                       <div class="span4 portfolio-item">
                            <br>
                            <h3> <b>You answered : </b>{% autoescape off %}{{ user_ans }}{% endautoescape %} {% if user_ans.correct == True %} <img src="{% static 'img/check_tick.png' %}" alt=""/> {% else %} <img src="{% static 'img/cross.png' %}" alt=""/> {% endif%} </h3>
                            <br>
                            <h3> <b>The correct answer is  :</b> {% autoescape off %}{{ corr_ans }}{% endautoescape %} </h3>
                       </div>



                    </div>
                    <!-- end: Row -->

                </div>
                <br>
            {% endfor %}
            <br>
            <div align="center">
                            <h3><font color="white" size="5"> Your score is {{ score }} out of {{ outof }} </font></h3>
            </div>
        {% else %}
            <h2 style="color:#ffffff;" align="center">No Questions Answered</h2>
        {% endif %}
	</div>
		<!--end: Container-->

  {% endblock %}

templates/quizzes/quizzes.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
    <!--start: Container -->
    <div class="container">

        {% if questions %}

            <div id="wrapper">

                <hr class="clean">

                <!-- start: Row -->
                <div align = "center" class="row">
                    <h1 CLASS="blue-heading-h1">{{ title }} Quiz</h1> <br>
                    <h3 CLASS="blue-heading-h3">Below you will find 15 random questions from a larger question bank.</h3>
                </div>
                <!-- end: Row -->

            </div>
            <br>

            <form name = "quiz" action="{% url 'app:checkans' %}" data-ajax=false  method="post">

                {% csrf_token %}
                {% for question1 in questions %}
                    <!--start: Wrapper-->
                    <div id="wrapper">

                        <hr class="clean">

                        <!-- start: Row -->
                        <div class="row">

                            <div align="justified">
                                <h2><font color = #002a80>&nbsp &nbsp  &nbsp {% autoescape off %}{{ forloop.counter }}. {{ question1.question }} {% endautoescape %}</font></h2>
                                <!-- hidden input to capture questions -->
                                <input type="hidden" name="ques[]" id="ques-{{forloop.counter}}" value="{{question1.number}}" data-theme="a"  />

                                <br>
                            </div>

                            <div align="left">
                                <h3> Select one: </h3>

                                {% for answer1 in answers %}
                                    {% if answer1.question == question1 %}
                                        <input type="radio" name="ans{{ forloop.parentloop.counter }}" id="ans-{{forloop.counter}}" value="{{answer1.number}}" data-theme="a"  /><font color="black" size="3"> {% autoescape off %}{{ answer1.answer }} {% endautoescape %}</font>
                                        <br><br>
                                    {% endif %}
                                {% endfor %}


                            </div>

                            <div> </div>


                        </div>
                        <!-- end: Row -->

                    </div>
                    <br>
                    <!--end: Container-->
                {% endfor %}

                <input id="checkButton" type="submit" data-role="button" data-icon="check" data-inline="true" data-theme="g" value="Check answer">
            </form>
        {% else %}
            <h2 style="color:#ffffff;" align="center">No Questions for This Section</h2>
        {% endif %}

    </div>
{% endblock %}