Molecular_Methods_Project/urls.py
from django.conf.urls import patterns, include, url
from yawdadmin import admin_site

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
admin_site._registry.update(admin.site._registry)

#Add any extra urls to applications or maybe log-in screen
urlpatterns = patterns('',
    # Examples:

    # url(r'^$', 'Molecular_Methods_Project.views.home', name='home'),
    # url(r'^Molecular_Methods_Project/', include('Molecular_Methods_Project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin_site.urls)),

    url(r'^app/', include('app.urls', namespace='app')),
    url(r'', include('app.urls', namespace='app')),
)

app/urls.py
from django.conf.urls import patterns,include, url
from app import views
from django.conf import settings
from django.contrib import admin

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^index/$', views.index, name='index'),
        url(r'^glossary/$', views.glossary, name='glossary'),
        url(r'^labs/$', views.labs, name='labs'),
        url(r'^admin/$', include(admin.site.urls)),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^videos/$', views.videos, name='videos'),
        url(r'^primersquizzes/$', views.primersquizzes, name='primersquizzes'),
        url(r'^checkans/$', views.checkans, name='checkans'),
        url(r'^generalquizzes/$', views.generalquizzes, name='generalquizzes'),
        url(r'^restrictionquizzes/$', views.restrictionquizzes, name='restrictionquizzes'),
        url(r'^dataquizzes/$', views.dataquizzes, name='dataquizzes'),
        url(r'^pcrlab/$', views.pcrlab, name='pcrlab'),
        url(r'^ligation/$', views.ligation, name='ligation'),
        url(r'^bwscreening/$', views.bwscreening, name='bwscreening'),
        url(r'^plasmid/$', views.plasmid, name='plasmid'),
        url(r'^dna/$', views.dna, name='dna'),
        url(r'^quantpcr/$', views.quantpcr, name='quantpcr'),
        url(r'^revision/$', views.revision, name='revision'),
        url(r'^converterconcentration/$', views.converterconcentration, name='converterconcentration'),
        url(r'^converterdilutions/$', views.converterdilutions, name='converterdilutions'),
        url(r'^convertermass/$', views.convertermass, name='convertermass'),
        url(r'^convertermolarity/$', views.convertermolarity, name='convertermolarity'),
        url(r'^convertervolume/$', views.convertervolume, name='convertervolume'),
        url(r'^mapping/$', views.mapping, name='mapping'),
        url(r'^pcrlabpdf/$', views.pcr_pdf_view, name='pcrlabpdf'),
        url(r'^ligationlabpdf/$', views.ligation_pdf_view, name='ligationlabpdf'),
        url(r'^bwslabpdf/$', views.bws_pdf_view, name='bwslabpdf'),
        url(r'^plasmidlabpdf/$', views.plasmid_pdf_view, name='plasmidlabpdf'),
        url(r'^dnalabpdf/$', views.dna_pdf_view, name='dnalabpdf'),
        url(r'^qpcrlabpdf/$', views.qpcr_pdf_view, name='qpcrlabpdf'),
        url(r'^Electrophoresis/$', views.electro_pdf_view, name='Electrophoresis'),
        url(r'^Sequence_Analysis/$', views.sa_pdf_view, name='Sequence_Analysis'),
        url(r'^Ligation_Calculations/$', views.lc_pdf_view, name='Ligation_Calculations'),
        url(r'^QPCR_Exercises/$', views.qpcrexer_pdf_view, name='QPCR_Exercises'),
        url(r'^Primer_Design_Exercise/$', views.pdexer_pdf_view, name='Primer_Design_Exercise'),
        url(r'^Restriction_Mapping_Exercise/$', views.rmexer_pdf_view, name='Restriction_Mapping_Exercise'),
        url(r'^lab_manual_pdf/$', views.lab_manual_pdf_view, name='lab_manual_pdf'),
        # end pdfs
        url(r'^searchResult/$', views.search, name='searchResult'),
        url(r'^resetConfirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/',views.reset_confirm, name='resetConfirm'),
        url(r'^pwdReset/', views.reset, name='pwdReset'),
        url(r'^about/', views.contact, name='about'),
        url(r'^thanks/', views.thanks, name='thanks'),

)


if settings.DEBUG:
        urlpatterns += patterns(
                'django.views.static',
                (r'static/(?P<path>.*)',
                'serve',
                {'document_root': settings.STATIC_ROOT}), )

templates/base.html
<!doctype html>
<html lang="en"><head>
    <link rel="shortcut icon" type="image/png" href="http://127.0.0.1:8000/static/img/favicon.png"/>
    <link rel="apple-touch-icon" href="http://molecularmethods.clinmed.gla.ac.uk/static/img/logo5.png"/>
    <link rel="apple-touch-icon-precomposed" href="http://molecularmethods.clinmed.gla.ac.uk/static/img/logo5.png"/>
</head><body class="Site">{% load staticfiles %}

<!-- start: Meta -->
<meta charset="utf-8">
<title>Molecular Methods WebApp</title>
<!-- end: Meta -->

<!-- start: Mobile Specific -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<!-- end: Mobile Specific -->

<!-- start: CSS -->
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700">
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Serif">
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Boogaloo">
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Economica:700,400italic">

<link rel="stylesheet" href="{% static 'css/style.css' %}"property="stylesheet">
<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}"property="stylesheet">
<!-- end: CSS -->
<!--start: Header -->
<header>
    <!--start: Container -->
    <div class="container">
        <!--start: Logos -->
        <nav class="navbar navbar-upper-logos hidden-xs" role="navigation">
            <a class="navbar-brand navbar-left" href="{% url 'app:index' %}"><img style="height: 50px; margin-top: -5px;" src=" {% static 'img/logo8.png' %}" alt="logo"></a>
            <a class="navbar-brand navbar-right" href="http://www.gla.ac.uk/"><img style="height: 50px; margin-top: -5px;" src="{% static 'img/glalogo1.png' %}" alt="glasgowlogo"></a>
        </nav>
        <div><br></div>
        <!--end: Logos -->

        <!-- Sound -->
        <div>
            <audio id="timerSound">
                <source src="{% static 'sound/timer_bell.mp3' %}" type="audio/mpeg">
            </audio>
        </div>
        <!--end: Sound -->

        <!--start: Navigation -->
        <nav class="navbar navbar-inverse navbar-default" role="navigation">
            <div class="container"></div>

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse">
                <!--<a class="navbar-brand" href="#">WebSiteName</a>-->
                <ul class="nav navbar-nav">

                    <li class=""><a href="{% url 'app:labs' %}">Labs</a></li>
                    <li><a href="{% url 'app:revision' %}">Revision</a></li>
                    <li><a href="{% url 'app:videos' %}">Videos</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Quizzes<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'app:generalquizzes' %}">General Molecular Methods</a></li>
                            <li><a href="{% url 'app:primersquizzes' %}">PCR and Primers</a></li>
                            <li><a href="{% url 'app:restrictionquizzes' %}">Restriction Mapping</a></li>
                            <li><a href="{% url 'app:dataquizzes' %}">Laboratory Calculations</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Exercises<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'app:mapping' %}">Restriction Mapping</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Converters<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'app:convertermass' %}">Mass Converter</a></li>
                            <li><a href="{% url 'app:convertervolume' %}">Volume Converter</a></li>
                            <li><a href="{% url 'app:convertermolarity' %}">Concentration(Molarity)</a></li>
                            <li><a href="{% url 'app:converterconcentration' %}">Concentration(%)</a></li>
                            <li><a href="{% url 'app:converterdilutions' %}">Dilution from Stocks</a></li>
                        </ul>
                    </li>
                    <li class=""><a href="{% url 'app:glossary' %}">Glossary</a></li>

                    <!--<li><a href="#" data-toggle="collapse" data-target="#demo">Timer</a></li>-->
                    <li class=""><a href="{% url 'app:about' %}">About</a></li>
                    <li id="custom-search-input">
                        <div style="position:relative; left:20px; bottom:3px;"  class="input-group col-md-12">
                            <form method="get" action="{% url 'app:searchResult' %}">
                                <input type="text" onfocus="if(this.value != '') {this.value=''}" name="q" id="id_q" placeholder="Search glossary ..." class="search-query form-control">
                            </form>
                            <div id="dialogTitle" title="">
                                <div id="dialogContent" align="justify"></div>
                            </div>
                        </div>
                    </li>
                    <li class="hidden-md" style="position:relative;" >

                        {% if user.is_authenticated %}

                        <a href="{% url 'app:logout' %}"><font color="white">Logout</font></a>

                        {% endif %}

                    </li>
                </ul>
                <div id="demo" class="collapse" style="width: 500px;height: 10px;">
                    <div id="dialogTimer" title="Timer">
                        <div id="dialogTimeUp"></div>
                    </div>

                    {# Timer javascript import#}
                    <script src="{% static 'js/timer.js' %}"></script>
                    <script> timer();</script>

                    <br>

                    <span class="btn-group" style="color:#fff">Time: </font> <input type="text" style="color:#004669; height: 25px; width: 152px" placeholder="enter number of seconds" name="time" id="time" size="5"><br>
                                  <!--Loop: <input type="checkbox" name="loop" id="loop"><br>-->
                        <button type="button" class="btn-small btn-danger" style="width:60px;height:25px;" id="reset" >Set</button>
                        <button type="button" class="btn-small btn-success" style="width:60px;height:25px;" id="start">Start</button>
                        <button type="button" class="btn-small btn-timer "style="width:60px;height:25px;" id="counter">0</button>
                    </span>

                    <br>
                </div>
            </div>
        </nav>
        <!--end: Navigation -->

    </div>
    <!--end: Row -->

    </div>
    <!--end: Container-->

</header>
<!--end: Header-->


<!--detect if the CDN-hosted /bootstrap.min.css fails to load-->
<div id="CssFailCheck" class="hidden" style="height:1px;"></div>

<div>
    {% block body_block %}{% endblock %}
</div>
<main class="Site-content"></main>
<!-- start: Under Footer -->
<div id="footer">

    <!-- start: Row -->

    <div class="row">

        <!-- start: Under Footer Logo -->
        <div class="col-sm-3 col-md-3">
            <div id="under-footer-logo">
                <a href="{% url 'app:index' %}"><font color="white"> Molecular Methods </font></a>
            </div>
        </div>
        <!-- end: Under Footer Logo -->

        <!-- start: Under Footer Copyright -->
        <div class="col-sm-8 col-md-8">

            <div id="under-footer-copyright" style="color:white">
                © 2014, Designed by Level 3 Computing Science Undergraduates for the School of Life Sciences</a>
            </div>
        </div>
        <!-- end: Under Footer Copyright -->

        <!-- start: Under Footer Back To Top -->
        <div class="col-sm-1 col-md-1">
            <div class="col-lg-offset-4 col-sm-10 col-md-10">
                <a href="#"><img src="{% static 'img/scroll-top-top.png' %}" alt="top"></a>
            </div>

        </div>
        <!-- end: Under Footer Back To Top -->
        <!-- end: Row -->
    </div>
    <!-- end: Under Footer -->
</div>
<!-- end: Container  -->

<script src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script><!--try to use CDN first-->
<script>window.jQuery || document.write('<script src="{% static 'js/jquery-2.1.3.min.js' %}"><\/script>')</script> <!--if CDN file isn't delivered, send a local file-->
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script defer="defer" src="{% static 'js/custom.js' %}"></script>
<script>
    $(document).ready(function() {
        $(window).keydown(function(event){
            if(event.keyCode == 13) {
                event.preventDefault();
                return false;
            }
        });
    });

</script>


<script type="text/javascript">
    $(function() {

        $( "#id_q" ).autocomplete({
            source: '/app/searchResult/',
            minLength: 2,
            select: function(event, ui) {

                event.preventDefault();
                $('#id_q').val(ui.item.label);


                // Title: ui.item.label
                // Description: ui.item.value

                // alert(ui.item.value);


                $("#dialogTitle").dialog({
                    autoOpen: true,
                    width: 400,
                    closeOnEscape:false,
                    draggable:true,
                    open: function () {
                        $("#dialogTitle").dialog("option", "title", ui.item.label)
                        $('.ui-dialog-titlebar-close').removeClass("ui-dialog-titlebar-close").html('<span>X</span>');
                    }
                });
                $("#dialogContent").text(ui.item.value);
            }
        });
    });
</script>
<script>
    // use local CSS file as fallback if Bootstrap CDN fails
    $(function () {
        if ($('#CssFailCheck').is(':visible') === true) {
            $('<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" property="stylesheet">').appendTo('head');
        }
    });
</script>
<!-- end: Java Script -->
</body></html>

templates/email_title.html
Forgotten Password

templates/labs.html
{% extends "base.html" %} {% load staticfiles %} {% block body_block %}
    <!--start:
    Container -->
    <div class="container">
        <!--start: Wrapper-->
        <div id="wrapper">
            <div class="row">

                <div class="col-md-6">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="http://www.youtube.com/embed/GgcGFyDvyFA"  style="border:4px solid #002a80;"></iframe>
                    </div>
                    <h3 class="blue-heading-h3 hidden-xs" style="font-weight: bold;"> Student perceptions of the Molecular Methods lab</h3>
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                        Lab Safety Animation
                    </button>
                </div>
                <div class="col-md-6">
                    <h1 class="blue-heading-h1 hidden-xs" > Molecular Methods Introduction</h1>
                    <br>
                    <h3 class="blue-heading-h3" style="text-align: justify;">Molecular Methods is a course designed to allow you to develop practical skills and understanding in molecular biology.

                        To accomplish this there are a number of linked experiments that you will perform to take you through a process from PCR to gene cloning, plasmid DNA preparation,

                        DNA sequencing and sequence analysis. The labs will build knowledge and confidence, allowing you to plan and perform your own experiments in the future!</h3>
                    <a href="{% url 'app:lab_manual_pdf' %}" title="Lab Manual">
                        <br />
                        <img src="{% static 'img/PDFicon.png' %}" width="12%" height="12%" align="left" alt="" class="img-responsive" />
                        <br />
                        <h2 class="blue-heading-h3"><i>Download the Lab Manual</i></h2></a>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <!--start: Wrapper-->
        <div id="wrapper">
            <hr class="clean" />
            <!-- start: Row -->
            <div class="row">
                <div class="col-md-2 portfolio-item">
                    <div class="picture"><a href="{% url 'app:pcrlab' %}" title="Lab 1"><img src="{% static 'img/lab1-PCR.png' %}" alt="" class="img-responsive"  style="max-width: 20pc"/><div class="image-overlay-link"></div></a>
                        <div
                                class="post-title" style="text-align: center;">
                            <h2><a href="{% url 'app:pcrlab' %}"><font color="#002a80">PCR</font></a></h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 portfolio-item">
                    <div class="picture"><a href="{% url 'app:ligation' %}" title="Lab 2"><img src="{% static 'img/lab2-LaT.png' %}" alt="" class="img-responsive" style="max-width: 20pc"/><div class="image-overlay-link"></div></a>
                        <div
                                class="post-title" style="text-align: center;">
                            <h2><a href="{% url 'app:ligation' %}"><font color="#002a80">Ligation and Transformation</font></a></h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 portfolio-item">
                    <div class="picture"><a href="{% url 'app:bwscreening' %}" title="Lab 3"><img src="{% static 'img/lab3-BWS.png' %}" alt="" class="img-responsive" style="max-width: 20pc"/><div class="image-overlay-link"></div></a>
                        <div
                                class="post-title" style="text-align: center;">
                            <h2><a href="{% url 'app:bwscreening' %}"><font color="#002a80">Blue/White Screening</font></a></h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 portfolio-item">
                    <div class="picture"><a href="{% url 'app:plasmid' %}" title="Lab 4"><img src="{% static 'img/lab4-PM.png' %}" alt="" class="img-responsive" style="max-width: 20pc" /><div class="image-overlay-link"></div></a>
                        <div
                                class="post-title" style="text-align: center;">
                            <h2><a href="{% url 'app:plasmid' %}"><font color="#002a80">Plasmid Miniprep</font></a></h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 portfolio-item">
                    <div class="picture"><a href="{% url 'app:dna' %}" title="Lab 5"><img src="{% static 'img/lab5-DNA.png' %}" alt="" class="img-responsive" style="max-width: 20pc"/><div class="image-overlay-link"></div></a>
                        <div
                                class="post-title" style="text-align: center;">
                            <h2><a href="{% url 'app:dna' %}"><font color="#002a80">DNA sequencing</font></a></h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 portfolio-item">
                    <div class="picture"><a href="{% url 'app:quantpcr' %}" title="Lab 6"><img src="{% static 'img/lab6-rtqPCR.png' %}" alt="" class="img-responsive " style="max-width: 20pc" /><div class="image-overlay-link"></div></a>
                        <div
                                class="post-title" style="text-align: center;">
                            <h2><a href="{% url 'app:quantpcr' %}"><font color="#002a80">Real-Time Quantitative PCR</font></a></h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title blue-heading-h3" id="myModalLabel" style="">Lab Safety</h4>
      </div>
      <div class="modal-body">
       <div class="embed-responsive embed-responsive-16by9"> <iframe class="embed-responsive-item " src="{% static 'img/Safety_Video_v02.mp4' %}" style="border:4px solid #002a80;"></iframe></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
            </div>
            <!-- end: Row -->
        </div>
        <!--end: Container-->
    </div>{% endblock %}

templates/reset_subject.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        http://molecularmethods.clinmed.gla.ac.uk{% url 'app:resetConfirm' uidb36=uid token=token %}
    {% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}Please do not reply to this email{% endblocktrans %}

{% endautoescape %}

templates/revision.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
    <div class="container">
        <!--start: Wrapper-->
        <div id="wrapper">
            <div class="row col-md-12">
                <h1 class="blue-heading-h1 page-header">PCR & Primers</h1>
                <div class="row col-md-8">
                    <!-- Nav tabs -->

                    <div id="myCarousel-pcr" class="carousel slide">
                        <!-- main slider carousel items -->
                        <div class="carousel-inner">
                            <div class="active item" data-slide-number="0">
                                <div class="embed-responsive-item">
                                    <div class="youtube hidden-xs " id="c-f1H07D_70" style="width: 640px; height: 360px;"></div>
                                    <div class="youtube visible-xs" id="c-f1H07D_70" style="width: 230px; height: 129px;"></div>
                                </div>
                            </div>
                        </div>
                        <br>
                    </div>
                </div>
                <div class="row col-md-6">
                    <div class="col-xs-4">
                        <a href="{% url 'app:primersquizzes' %}" title="Quiz"><img src="{% static 'img/quiz.png' %}" class="img-responsive  "/>
                            <div class="image-overlay-link"></div>
                        </a>
                    </div>
                    <div class="col-xs-4">
                        <a href="{% url 'app:Primer_Design_Exercise' %}" title="Exercise"><img src="{% static 'img/exercise_caption.png' %}" class="img-responsive "/></a>
                        <div class="image-overlay-link"></div>
                        <br>
                    </div>
                </div> <!--end: Row -->
            </div>
            <br>
            <!-- start: Row -->
            <div class="row col-md-12">
                <h1 class="blue-heading-h1 page-header">Restriction Mapping</h1>
                <div class="row col-md-8">
                    <!-- Nav tabs -->
                    <div id="myCarousel" class="carousel slide">
                        <!-- main slider carousel items -->
                        <div class="carousel-inner">
                            <div class="active item" data-slide-number="0">
                                <div class="embed-responsive-item">
                                    <div class="youtube hidden-xs " id="yR_heZ4n4Gc" style="width: 640px; height: 360px;"></div>
                                    <div class="youtube visible-xs" id="yR_heZ4n4Gc" style="width: 230px; height: 129px;"></div>
                                </div>
                            </div>
                            <div class="item" data-slide-number="1">
                                <div class="embed-responsive-item">
                                    <div class="youtube hidden-xs" id="MeTWD8ECeiQ" style="width: 640px; height: 360px;"></div>
                                    <div class="youtube visible-xs" id="MeTWD8ECeiQ" style="width: 230px; height: 129px;"></div>
                                </div>
                            </div>
                        </div>
                        <nav>
                            <ul class="pager">
                                <li class="previous"><a href="#myCarousel" data-slide="prev">
                                    Prev
                                    <span class="sr-only">Previous</span></a></li>
                                <li class="next"><a href="#myCarousel"data-slide="next">Next
                                    <span class="sr-only">Next</span></a></li>
                            </ul>
                        </nav>

                    </div>
                    <br>
                </div>
                <div class="row col-md-6">
                    <div class="col-xs-4">
                        <a href="{% url 'app:restrictionquizzes' %}" title="Quiz"><img src="{% static 'img/quiz.png' %}" class="img-responsive  "/>
                            <div class="image-overlay-link"></div>
                        </a>
                    </div>
                    <div class="col-xs-4">
                        <a href="{% url 'app:Restriction_Mapping_Exercise' %}" title="Exercise"><img src="{% static 'img/exercise_caption.png' %}" class="img-responsive "/>
                            <div class="image-overlay-link"></div>
                        </a>
                        <br>
                    </div>
                    <div class="col-xs-4">
                        <a href="{% url 'app:mapping'%}" title="Exercise"><img src="{% static 'img/rsmap_exer.png' %}" class="img-responsive "/>
                            <div class="image-overlay-link"></div>
                        </a>
                        <br>
                    </div>
                </div>
            </div> <!--end: Row -->
            <br>
            <!-- start: Row -->
            <div class="row col-md-12">
                <h1 class="blue-heading-h1 page-header">Laboratory Calculations</h1>
                <div class="row col-md-8">
                    <!-- Nav tabs -->
                    <div id="myCarousel2" class="carousel slide">
                        <!-- main slider carousel items -->
                        <div class="carousel-inner">
                            <div class="active item" data-slide-number="0">
                                <div class="embed-responsive-item">
                                    <div class="youtube hidden-xs " id="vOwdQRBENJQ" style="width: 640px; height: 360px;"></div>
                                    <div class="youtube visible-xs" id="vOwdQRBENJQ" style="width: 230px; height: 129px;"></div>
                                </div>
                            </div>
                            <div class="item" data-slide-number="1">
                                <div class="embed-responsive-item">
                                    <div class="youtube hidden-xs" id="pVNpFP2Wmlc" style="width: 640px; height: 360px;"></div>
                                    <div class="youtube visible-xs" id="pVNpFP2Wmlc" style="width: 230px; height: 129px;"></div>
                                </div>
                            </div>
                            <div class="item" data-slide-number="1">
                                <div class="embed-responsive-item">
                                    <div class="youtube hidden-xs" id="vHx4nqRdpMg" style="width: 640px; height: 360px;"></div>
                                    <div class="youtube visible-xs" id="vHx4nqRdpMg" style="width: 230px; height: 129px;"></div>
                                </div>
                            </div>



                        </div>

                        <nav>
                            <ul class="pager">
                                <li class="previous"><a href="#myCarousel2" data-slide="prev">
                                    Prev
                                    <span class="sr-only">Previous</span></a></li>
                                <li class="next"><a href="#myCarousel2"data-slide="next">Next
                                    <span class="sr-only">Next</span></a></li>
                            </ul>
                        </nav>
                    </div>
                    <br>
                </div>
                <div class="row col-md-6">
                    <div class="col-xs-4">
                        <a href="{% url 'app:dataquizzes' %}" title="Quiz"><img src="{% static 'img/quiz.png' %}" class="img-responsive"/>
                            <div class="image-overlay-link"></div>
                        </a>
                    </div>
                    <div class="col-xs-4">
                        <a href="{% url 'app:Ligation_Calculations' %}" title="Exercise"><img src="{% static 'img/exercise_caption.png' %}" class="img-responsive "/>
                            <div class="image-overlay-link"></div></a>
                        <br>
                    </div>
                </div> <!--end: Row -->
            </div>
        </div> <!--end: container -->
    </div><!--end: wrapper -->
    </div>
    </div>
    </div>

    <script src="https://labnol.googlecode.com/files/youtube.js"></script>




{% endblock %}